GET http://localhost:8080/invoice/find-all-invoice-by-customerId/1
Accept: application/json

###
GET http://localhost:8080/customer/find-customer-by-accountId/1
Accept: application/json

###
GET http://localhost:8080/car/find-all-car-by-customerId/1
Accept: application/json

###
GET http://localhost:8080/account/findAll
Accept: application/json

###
GET http://localhost:8080/account/confirmPassword/1
Content-Type: application/json

{
  "passwordOld": "456"
}

###

POST http://localhost:8080/account/setVerifyCode/1
Content-Type: application/json

{
  "verificationCode": "AOa70kgy"
}

###
PUT http://localhost:8080/account/changePassword/1
Content-Type: application/json

{
  "verificationCode": "WzINCkS6",
  "passwordNew": "1322"
}

###
PUT http://localhost:8080/account/savePassword/1
Content-Type: application/json

{
  "passwordNew": "123"
}


###
PUT http://localhost:8080/account/changePassword/1
Content-Type: application/json

{
  "verificationCode": "ykTNj1U8"
}

###