POST http://localhost:8080/statistic/total-revenue-ticket-period
Content-Type: application/json

{
  "fromDayPayment": "2019-12-10",
  "toDayPayment": "2022-09-26"
}

###
POST http://localhost:8080/statistic/total-revenue-member-card-period
Content-Type: application/json

{
  "fromDayPayment": "2019-12-10",
  "toDayPayment": "2022-09-26"
}

###
POST http://localhost:8080/statistic/total-customer-register-period
Content-Type: application/json

{
  "fromDay": "2020-12-10",
  "toDay": "2021-09-26"
}

###
GET http://localhost:8080/statistic/total-car-type-parking-slot
Accept: application/json

###
GET http://localhost:8080/statistic/total-customer
Accept: application/json

###
GET http://localhost:8080/statistic/total-employee
Accept: application/json

###
GET http://localhost:8080/statistic/total-car-parking
Accept: application/json

###
GET http://localhost:8080/statistic/total-parking-slot
Accept: application/json

###
GET http://localhost:8080/statistic/total-member-card-type
Accept: application/json

###
GET http://localhost:8080/statistic/total-car-of-customer
Accept: application/json

###